Fixing: Unknown options: env, parserOptions, rules. XXXX has been removed. Please use the 'overrideConfig.XXXX' option instead.
Error: Invalid Options:
- Unknown options: env, parserOptions, rules
- 'parserOptions' has been removed. Please use the 'overrideConfig.parserOptions' option instead.
- 'rules' has been removed. Please use the 'overrideConfig.rules' option instead.